### ISSUE TITLE
Rewrite tests with node assert

### ISSUE THREAD

**Issue by GrosSacASac** [GrosSacASac/emitter#6]
Drop mocha from dev dependencies

Use node assert for testing, most test will need to rewritten because API is different

https://nodejs.org/api/assert.html

Use similar syntax for launching tests:
`node --experimental-modules my-test.mjs`

**Comment by rjjuina** [comment]
@GrosSacASac Please help to review - https://github.com/GrosSacASac/event-e3/pull/7

**Comment by GrosSacASac** [comment]
Thanks
